In [2]:
%pylab inline

import numpy as np
import pandas as pd
import math as m
import cvxpy as cvx
from sklearn.metrics import accuracy_score,confusion_matrix
import random as rnd
import functools as fu

indxes = [str(x) for x in range(1,114)]
heroes = ["Victory","Ping","Radiant","Dire"]+indxes
train = pd.read_csv("d2Train.csv",names=heroes)
test  = pd.read_csv("d2Test.csv",names=heroes)

X_train = train[indxes]
Y_train = train["Victory"]

X_test = test[indxes]
Y_test = test["Victory"]

fs_train = np.matrix(X_train).T
ts_train = np.matrix(Y_train).T
fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T

d_margin = ts_train.T*fs_train.T;

Populating the interactive namespace from numpy and matplotlib


/usr/src/anaconda3/lib/python3.5/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['test']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [37]:
train

Victory  Ping  Radiant  Dire  1  2  3  4  5  6 ...   104  105  106  \
0           -1   223        2     2  0  0  0  0  0  0 ...     0    0    0   
1            1   152        2     2  0  0  0  1  0 -1 ...     0    0    0   
2            1   131        2     2  0  0  0  1  0 -1 ...     0    0    0   
3            1   154        2     2  0  0  0  0  0  0 ...    -1    0    0   
4           -1   171        2     3  0  0  0  0  0 -1 ...     0    0    0   
5            1   122        2     3  0  1  0  0  0  0 ...     1    0    0   
6            1   224        8     3  0  0  0  0  0  0 ...     0    0    0   
7           -1   227        8     3  0 -1  0  0  0  0 ...     0    0    0   
8           -1   111        2     3  0  0  1  0  0  0 ...     0    1    0   
9           -1   151        2     2  0  0  0  1  0  0 ...     0    0    1   
10           1   145        2     3  0  1  0  0  1  1 ...     1    0    0   
11          -1   231        2     2 -1  0  1  0  0  0 ...    -1    0    0   
12          -1   188        2     2  0  0  0  0  0  0 ...     0    0    0   
13          -1   156        2     3  0  1  0  0 -1 -1 ...     0    0    0   
14          -1   188        2     2  0  0  0  1  0  0 ...     0    0    0   
15          -1   144        2     3  0  0  0 -1  0  1 ...    -1    0    0   
16           1   153        2     2  0  0  0  0  0  0 ...     0    0    0   
17           1   227        2     3  0  0  0  0  0 -1 ...     0    0    0   
18           1   153        2     2  0  0  0  1  0  0 ...     1    0    0   
19          -1   225        8     3  1  0  0 -1  0  0 ...     0    0    0   
20          -1   155        2     2  0  0  0  0  0 -1 ...    -1    1    0   
21           1   186        2     2  0  0  0  0  0  0 ...     0    0    0   
22          -1   181        2     3  0  0  0  0  0  0 ...     0    0    0   
23           1   171        2     2  0  0  0  0 -1  0 ...     0    0    0   
24           1   183        8     3  0  0  0  0 -1  0 ...     0    0    0   
25          -1   145        2     2  0  0  0  0  0  1 ...     0    0    0   
26          -1   145        2     2  0  0  0  0  0  0 ...     0    0    0   
27           1   156        2     3  0  0  0  0  0  0 ...     0    0    0   
28           1   156        2     2  1  0  0  1  0  0 ...     0   -1    0   
29          -1   121        6     2  0  0  0  0  0  0 ...     0    0    1   
...        ...   ...      ...   ... .. .. .. .. .. .. ...   ...  ...  ...   
92620       -1   136        2     3  0  0  0  0  0  0 ...    -1    0    0   
92621       -1   154        2     2  0  0  0  0  0  0 ...     0    0   -1   
92622        1   153        2     2  0  0  0  0  0  0 ...    -1    0    0   
92623       -1   227        2     2  1  0  0  0  0  0 ...     0    0    0   
92624        1   151        2     2  0  1  0  0  0  0 ...     0    0    0   
92625        1   123        2     3  1  0  0  0 -1  0 ...     0    0    0   
92626        1   224        9     2  0  0  0  0  0  1 ...     0    1    0   
92627       -1   156        2     2  0  0  0  0  0  1 ...    -1    0    0   
92628       -1   204        2     3 -1  1  0  0  0  0 ...     0    0    0   
92629       -1   152        2     2  0  1  0  0  0 -1 ...     0    0    0   
92630       -1   154        2     2  0  0  0  0  0  0 ...     0    1    0   
92631       -1   186        2     2  0  0  0  0  0  0 ...     0    0    0   
92632        1   152        2     2  0 -1  0  0  0 -1 ...     0    0    0   
92633        1   155        2     2  0  0  0  1  0  0 ...     1    0    0   
92634       -1   155        2     3  0  0  0  0  0  0 ...     0    0    0   
92635        1   171        2     2  1 -1  0  0  0  0 ...     1    0    0   
92636        1   156        9     2  0  0  0  0  0  0 ...     0    0    1   
92637        1   151        2     3 -1  0  0  0  0  0 ...     0    0    0   
92638       -1   261        2     2  1  0  0 -1  0  0 ...     0    0    0   
92639        1   122        2     3  0  0  0 -1  0  1 ...     0    0    0   
926

In [38]:
test

Victory  Ping  Radiant  Dire  1  2  3  4  5  6 ...   104  105  106  \
0           -1   223        8     2  0 -1  0  0  0  0 ...    -1    0    0   
1            1   227        8     2  0  0  0  0  0  0 ...    -1    0    0   
2           -1   136        2     2  1  0  0  0 -1  0 ...     0    0    0   
3            1   227        2     2 -1  0  0  0  0  0 ...     0    0    0   
4            1   184        2     3  0  0  0 -1  0  0 ...     0    0    0   
5            1   231        2     2  0  0  0  0  0  0 ...     0    0    0   
6            1   152        2     2  0  0  0  0  0 -1 ...     0    1    0   
7           -1   153        2     2  1  0  0  0  0  0 ...     0    0    0   
8           -1   223        8     2  0  0  0  0  0  0 ...     0    0    0   
9           -1   153        2     2  0  0  0  0 -1  1 ...     0    0    0   
10          -1   133        9     2  0  0  0  0  0  1 ...     0    0    0   
11          -1   124        2     3  0  0  0  1  0  0 ...     0    0    0   
12           1   154        2     3  0  0  0  1  0  0 ...     0    0    0   
13           1   151        2     2 -1  0  0  0  0  0 ...     0    0   -1   
14          -1   223        9     2  0  0  0  0  0  0 ...     0    0    0   
15           1   154        2     3  0  0  0  0  0  0 ...     0    0    0   
16          -1   227        2     3  0 -1  0  0  0 -1 ...     0    0    0   
17          -1   224        2     3  0  0  0  0  0  0 ...     0    0    0   
18           1   225        2     2  0  0  0  0  0  0 ...     1    0    0   
19          -1   187        2     2  0  0  0  0  0  0 ...     0    0    0   
20          -1   225        8     3  0  0  0  0  0  1 ...     0    0    0   
21          -1   152        2     3  0 -1  0  0  0 -1 ...     0    0    0   
22          -1   231        2     2  1  0  0  0  0 -1 ...     0    0    0   
23           1   156        2     2  0  0  0  1  0  1 ...     1    0    0   
24           1   227        2     2  0  0  0  0  0  0 ...     0    0    0   
25          -1   137        2     3  0  0  0  0  0  0 ...     0    0    0   
26          -1   131        2     2  0  0  0  0  0  0 ...     0    0    0   
27          -1   136        2     3  0  0  0  0  0  0 ...     0    0    0   
28          -1   155        2     3  1  0  0  0 -1  0 ...     0    0    0   
29          -1   227        2     3  1  0  0  0  0  0 ...     0    0    0   
...        ...   ...      ...   ... .. .. .. .. .. .. ...   ...  ...  ...   
10264        1   188        9     2  0  0  0 -1  0  0 ...     0    0    0   
10265        1   185        2     2 -1  1  0  0  0  0 ...     0    0    0   
10266        1   204        2     2  0  0  0  0  1 -1 ...     0    0    0   
10267        1   227        2     2 -1  0  0  0  0  0 ...     0    0    0   
10268        1   225        2     3  0  0  0  0  0  0 ...     0    0    0   
10269       -1   187        2     3  0  0  0  0  0  0 ...    -1    0    0   
10270        1   151        2     2  0  0  0  0  0  0 ...     0    0    0   
10271        1   227        2     2  0  1  0  0  0  0 ...     0    0    0   
10272        1   227        2     2  0 -1  0  0  0  0 ...     0    0    0   
10273       -1   152        2     2  0  0  0  0 -1  0 ...    -1    0    0   
10274        1   134        2     3  0  0  0  0  0 -1 ...    -1    0   -1   
10275       -1   151        2     2  0  0  0  0  1  0 ...     0    0    0   
10276        1   227        4     2  0  0  0  0  0  0 ...     0    0    0   
10277       -1   152        2     2  0  0  0  0 -1  0 ...     0   -1    0   
10278       -1   156        2     3  0  0  0  0  1 -1 ...     0    0    0   
10279       -1   156        9     2  0  0  0  0  0  0 ...    -1    0    0   
10280       -1   188        2     3  0 -1  0  0  0  0 ...     1    0    0   
10281       -1   225        2     2  0  0  0  1  0  0 ...    -1    0    0   
10282       -1   156        2     2  0  0  0  0  0 -1 ...     0    0    1   
10283        1   187        2     2  0  0  0 -1  1  0 ...     0    0    0   
102

## Interim functions

In [3]:
def margin(w,v,z):
    return w.T*v*z

In [4]:
def objective_func(w):
    return m.log(1+m.exp(-(margin(w,fs_train,ts_train))),m.e)

def dobjective_func(w):
    return (-d_margin*(m.exp(-margin(w,fs_train,ts_train)))/(1+m.exp(-margin(w,fs_train,ts_train)))).T


In [5]:
def d(X):
    return 0.5*cvx.norm(X)**2

def dd(X):
    return X

### Additional distribution of teams

In [6]:
def additional_features(df):
    rad_dums =  pd.get_dummies(df["Radiant"])
    dire_dums = pd.get_dummies(df["Dire"])
    rad_dums.columns =  ["R"+str(i) for i in range(1,10)]
    dire_dums.columns = ["D"+str(i) for i in range(1,4)]
    return pd.concat([rad_dums,dire_dums],axis=1)

# Fast Gradient Method

### Model on addiatonal distrubition

In [7]:
X_train = train[indxes]
Y_train = train["Victory"]
X_train = pd.concat([X_train,additional_features(train)],axis=1)


X_test = test[indxes]
Y_test = test["Victory"]
X_test = pd.concat([X_test,additional_features(test)],axis=1)


fs_train = np.matrix(X_train).T
ts_train = np.matrix(Y_train).T
fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T

d_margin = ts_train.T*fs_train.T;

n = X_train.shape[1]
x = np.matrix([1/n]*n).T
k = 0
L = 1000
a_vs = [1/L]
y_vs = [x]
u_vs = [x]
x_vs = [x]
while True:
    print(k)
    sum_a = sum(a_vs)
    a_vs.append((1+m.sqrt(1+4*L*L*a_vs[k]*a_vs[k]))/(2*L))
    y_vs.append((a_vs[k+1]*u_vs[k]+sum(a_vs)*x_vs[k]))
    
    x = cvx.Variable(n)
    objective = cvx.Minimize((a_vs[k+1]*dobjective_func(y_vs[k+1]) -dd(u_vs[k])).T*x+d(x))
    prob = cvx.Problem(objective)
    prob.solve()
    u_vs.append(x.value)
    
    x_vs.append((a_vs[k+1]*u_vs[k+1]+sum_a*x_vs[k])/sum(a_vs))
    
    if abs(objective_func(x_vs[k+1]) - objective_func(x_vs[k]) < 0.00000000000000000000000000000000000000001):
        break
    k+=1
test_status = sign(x_vs[k+1].T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

first_method = x_vs[k+1]

0
Confusion matrix is:
[[ 375  227]
 [4417 5275]]
Accuracy score is: 0.548863415582


### Baseline model working only on heroes distribution

In [8]:
X_train = train[indxes]
Y_train = train["Victory"]

X_test = test[indxes]
Y_test = test["Victory"]

fs_train = np.matrix(X_train).T
ts_train = np.matrix(Y_train).T
fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T

d_margin = ts_train.T*fs_train.T;

n = X_train.shape[1]
x = np.matrix([1/n]*n).T
k = 0
L = 10000000000
a_vs = [1/L]
y_vs = [x]
u_vs = [x]
x_vs = [x]
while True:
    print(k)
    sum_a = sum(a_vs)
    a_vs.append((1+m.sqrt(1+4*L*L*a_vs[k]*a_vs[k]))/(2*L))
    y_vs.append((a_vs[k+1]*u_vs[k]+sum(a_vs)*x_vs[k]))
    
    x = cvx.Variable(n)
    objective = cvx.Minimize((a_vs[k+1]*dobjective_func(y_vs[k+1]) -dd(u_vs[k])).T*x+d(x))
    prob = cvx.Problem(objective)
    prob.solve()
    u_vs.append(x.value)
    
    x_vs.append((a_vs[k+1]*u_vs[k+1]+sum_a*x_vs[k])/sum(a_vs))
    
    if abs(objective_func(x_vs[k+1]) - objective_func(x_vs[k]) < 0.00000000000000000000000000000000000000001):
        break
    k+=1
test_status = sign(x_vs[k+1].T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

second_method = x_vs[k+1]

0
Confusion matrix is:
[[2782 2346]
 [2010 3156]]
Accuracy score is: 0.576840878181


### Averaging of weights

In [9]:
k = first_method.shape[0]-second_method.shape[0]
avg = (first_method[k:]+second_method)/2


#### Averaging  baseline weights

In [10]:
X_test = test[indxes]
Y_test = test["Victory"]

fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T


test_status = sign(avg.T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

Confusion matrix is:
[[2424 2787]
 [2368 2715]]
Accuracy score is: 0.499222848261


#### Averaging baseline with continious concatenetion

In [12]:
X_test = test[indxes]
Y_test = test["Victory"]
X_test = pd.concat([X_test,additional_features(test)],axis=1)


fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T


test_status = sign(np.concatenate([first_method[:k],avg]).T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

Confusion matrix is:
[[ 873  657]
 [3919 4845]]
Accuracy score is: 0.555469205362


# Mirrors Descent Method

### None smooth functions

In [18]:
def obj_func(X):
    return 2*cvx.norm(1-margin(X,fs_train,ts_train),2)
def dobj_func(X):
    return d_margin.T*(1/np.sqrt(1-margin(X,fs_train,ts_train))).T*(1/np.sqrt(1-margin(X,fs_train,ts_train)))

### Baseline model working only on heroes distribution

In [19]:
X_train = train[indxes]
Y_train = train["Victory"]

X_test = test[indxes]
Y_test = test["Victory"]

fs_train = np.matrix(X_train).T
ts_train = np.matrix(Y_train).T
fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T 

d_margin = ts_train.T*fs_train.T;


n = X_train.shape[1]
L  = 10000
x = np.matrix([0]*n).T
c_s = [np.random.uniform(low=0.0001, high=0.01, size=(1,))[0]] 
w_s = [x]
k = 0
f_t = 1000000
w_t = x


while True:
    c_s.append(np.random.uniform(low=0.0001, high=0.01, size=(1,))[0])
    t = cvx.Variable(n)
    objective = cvx.Minimize((c_s[k]*dobj_func(w_s[k]) - dd(w_s[k])).T*t+d(t))
    
    prob = cvx.Problem(objective)
    prob.solve()
    w_s.append(t.value)
    #print(k)
    
    agg = list((map((lambda x :x[0]*x[1]),zip(w_s,c_s))))
    x_t = sum(c_s)**(-1)*fu.reduce(lambda a,b: a+b, agg[1:],agg[0])
    
    if (f_t > obj_func(w_s[k]).value):
        w_t = w_s[k]
    f_v = max(obj_func(w_t).value,obj_func(x_t).value)
    
    if ((-f_v + obj_func(w_s[k+1]).value) <((-d(x).value + d(w_s[k+1]).value + dd(x).T*(w_s[k+1]-x) + 0.5*L*L*sum(list(map((lambda x:x**2),c_s))))/sum(c_s))):
        break
    k+=1

test_status = sign(w_s[k+1].T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))
third_method = w_s[k+1]
    


Confusion matrix is:
[[2010 3156]
 [2782 2346]]
Accuracy score is: 0.423159121819


### Model on addiatonal distrubition

In [20]:
X_train = train[indxes]
Y_train = train["Victory"]
X_train = pd.concat([X_train,additional_features(train)],axis=1)


X_test = test[indxes]
Y_test = test["Victory"]
X_test = pd.concat([X_test,additional_features(test)],axis=1)


fs_train = np.matrix(X_train).T
ts_train = np.matrix(Y_train).T
fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T

d_margin = ts_train.T*fs_train.T;


n = X_train.shape[1]
L  = 10000
x = np.matrix([0]*n).T
c_s = [np.random.uniform(low=0.0001, high=0.01, size=(1,))[0]] 
w_s = [x]
k = 0
f_t = 1000000
w_t = x


while True:
    c_s.append(np.random.uniform(low=0.0001, high=0.01, size=(1,))[0])
    t = cvx.Variable(n)
    objective = cvx.Minimize((c_s[k]*dobj_func(w_s[k]) - dd(w_s[k])).T*t+d(t))
    
    prob = cvx.Problem(objective)
    prob.solve()
    w_s.append(t.value)
    #print(k)
    
    agg = list((map((lambda x :x[0]*x[1]),zip(w_s,c_s))))
    x_t = sum(c_s)**(-1)*fu.reduce(lambda a,b: a+b, agg[1:],agg[0])
    
    if (f_t > obj_func(w_s[k]).value):
        w_t = w_s[k]
    f_v = max(obj_func(w_t).value,obj_func(x_t).value)
    
    if ((-f_v + obj_func(w_s[k+1]).value) <((-d(x).value + d(w_s[k+1]).value + dd(x).T*(w_s[k+1]-x) + 0.5*L*L*sum(list(map((lambda x:x**2),c_s))))/sum(c_s))):
        break
    k+=1

test_status = sign(w_s[k+1].T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))
fourth_method = w_s[k+1]
    
    


Confusion matrix is:
[[4410 5268]
 [ 382  234]]
Accuracy score is: 0.451136584418


In [34]:
k = fourth_method.shape[0]-third_method.shape[0]
avg = (fourth_method[k:]+third_method)/2

In [441]:
X_test = test[indxes]
Y_test = test["Victory"]

fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T


test_status = sign(avg.T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

Confusion matrix is:
[[2020 3122]
 [2772 2380]]
Accuracy score is: 0.427433456382


In [27]:
X_test = test[indxes]
Y_test = test["Victory"]
X_test = pd.concat([X_test,additional_features(test)],axis=1)


fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T


test_status = sign(np.concatenate([fourth_method[:k],avg]).T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

Confusion matrix is:
[[3903 4837]
 [ 889  665]]
Accuracy score is: 0.443753642899


## Global Averaging of weights from both models

In [35]:
X_test = test[indxes]

Y_test = test["Victory"]
X_test = pd.concat([X_test,additional_features(test)],axis=1)


fs_test = np.matrix(X_test).T
ts_test = np.matrix(Y_test).T


test_status = sign(((np.concatenate([fourth_method[:k],avg])+first_method)/2).T*fs_test).T
print("Confusion matrix is:")
print(confusion_matrix(test_status,ts_test))
print("Accuracy score is:",accuracy_score(test_status,ts_test))

Confusion matrix is:
[[3721 4646]
 [1071  856]]
Accuracy score is: 0.444627938605
